#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Regenerates the AUTO-STATUS block in docs/STATUS.md from real check
# results. Computed, not narrated: the block is proof, refreshed on
# every run. Never hand-edit between the markers.
#
# Exits non-zero if any check fails, so it can gate sessions and skills.
set -uo pipefail
cd "$(dirname "$0")/.."

status_file="docs/STATUS.md"
begin_marker='AUTO-STATUS:BEGIN'
end_marker='AUTO-STATUS:END'
checks=(doc-refs contract-conformance vmtest-wiring)

grep -q "$begin_marker" "$status_file" || { echo "status.sh: $begin_marker missing from $status_file" >&2; exit 1; }
grep -q "$end_marker" "$status_file" || { echo "status.sh: $end_marker missing from $status_file" >&2; exit 1; }

timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
sha=$(git rev-parse --short HEAD)
failed=0
lines=""
for check in "${checks[@]}"; do
  if nix build --no-link ".#checks.x86_64-linux.$check" >/dev/null 2>&1; then
    lines+="- \`$check\` — PASS"$'\n'
  else
    lines+="- \`$check\` — FAIL"$'\n'
    failed=1
  fi
done

block="<!-- $begin_marker (regenerated by scripts/status.sh — do not hand-edit) -->"$'\n'"Regenerated: $timestamp — git $sha"$'\n'"$lines""<!-- $end_marker -->"

awk -v block="$block" '
  $0 ~ /AUTO-STATUS:BEGIN/ { print block; skip = 1; next }
  skip && $0 ~ /AUTO-STATUS:END/ { skip = 0; next }
  !skip { print }
' "$status_file" > "$status_file.tmp" && mv "$status_file.tmp" "$status_file"

if [ "$failed" -ne 0 ]; then
  echo "status.sh: FAIL — see $status_file AUTO-STATUS block" >&2
  exit 1
fi
echo "status.sh: all ${#checks[@]} checks PASS"
