# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cococoir remote infra — the edge box.
#
# One Hetzner VPS with a single public IPv4 and a routed /64 IPv6
# subnet (every Hetzner server gets the /64 free — that is the 64–256
# address pool from the vision doc). The customer's /128 is derived
# from the /64 via cidrhost so DNS and the NixOS config cannot drift.
#
# The NixOS configs (edge.nix / example123.nix) are RENDERED from
# templates below: IPs, /64, WG subnet, and the WG public keys all
# flow from tofu so there is exactly one source of truth for the
# deployed addressing. WG private keys live in remote-infra/.secrets/
# (gitignored), never in the repo or the rendered configs.

locals {
  customer_ipv6   = cidrhost(hcloud_server.edge.ipv6_network, 2) # <subnet>::2
  edge_primary_v6 = cidrhost(hcloud_server.edge.ipv6_network, 1) # <subnet>::1
  edge_wg_ip      = cidrhost(var.wg_subnet, 1)                   # 10.10.0.1
  customer_wg_ip  = cidrhost(var.wg_subnet, 2)                   # 10.10.0.2

  # WG public keys — generated by scripts/gen-wg-keys.sh into
  # .secrets/ before `tofu apply`. Public keys are not secrets; the
  # PRIVATE halves stay in .secrets/ (gitignored) and are scp'd to
  # the boxes at provision time, never rendered into the repo.
  edge_wg_pub     = trimspace(file("${path.module}/../.secrets/wg/edge.pub"))
  customer_wg_pub = trimspace(file("${path.module}/../.secrets/wg/customer.pub"))
}

resource "hcloud_ssh_key" "operator" {
  name       = "cococoir-operator"
  public_key = var.ssh_public_key
}

resource "hcloud_firewall" "edge" {
  name = "${var.server_name}-firewall"

  # SSH — operator access + nixos-anywhere bootstrap.
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "22"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # HTTP / HTTPS — the forwarded customer traffic (ACME included).
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "80"
    source_ips = ["0.0.0.0/0", "::/0"]
  }
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "443"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # WireGuard — the customer's dial-out tunnel.
  rule {
    direction  = "in"
    protocol   = "udp"
    port       = tostring(var.wg_listen_port)
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # ICMP (ping) — reachability debugging for the demo.
  rule {
    direction  = "in"
    protocol   = "icmp"
    source_ips = ["0.0.0.0/0", "::/0"]
  }
}

resource "hcloud_server" "edge" {
  name         = var.server_name
  server_type  = var.server_type
  location     = var.location
  image        = var.bootstrap_image
  ssh_keys     = [hcloud_ssh_key.operator.id]
  firewall_ids = [hcloud_firewall.edge.id]

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true # -> routed /64 subnet
  }
}
