# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Cococoir remote infra — input variables.
#
# Public/derived values only. The single secret (Hetzner API token)
# comes from the HCLOUD_TOKEN env var. WireGuard private keys are
# generated by scripts/gen-wg-keys.sh into remote-infra/.secrets/
# (gitignored) and the PUBLIC halves are read from there by tofu —
# public keys are not secrets and may be committed if you want.
variable "server_name" {
  description = "Name of the edge box."
  type        = string
  default     = "edge"
}

variable "server_type" {
  description = "Hetzner server type for the edge box."
  type        = string
  default     = "cx22"
}

variable "location" {
  description = "Hetzner location (nbg1, fsn1, hel1, ash, sin)."
  type        = string
  default     = "nbg1"
}

variable "bootstrap_image" {
  description = "Disposable image nixos-anywhere overwrites with NixOS. Hetzner has no first-party NixOS image (confirmed via changelog 2026-08)."
  type        = string
  default     = "ubuntu-24.04"
}

variable "edge_interface" {
  description = "Primary NIC name on the edge box (ens3 on Hetzner amd64, enp1s0 on arm64). Verify with `ip addr` after first boot."
  type        = string
  default     = "ens3"
}

variable "ipv4_gateway" {
  description = "Hetzner IPv4 gateway (onlink). Same 172.31.1.1 across locations."
  type        = string
  default     = "172.31.1.1"
}

variable "domain" {
  description = "Apex domain the customer services live under (e.g. interdim.net)."
  type        = string
}

variable "customer" {
  description = "Customer username. *.&lt;customer&gt;.&lt;domain&gt; AAAA records point at their /128 on the edge box."
  type        = string
  default     = "example123"
}

variable "ssh_public_key" {
  description = "Operator SSH public key injected into the edge box and used by nixos-anywhere."
  type        = string
}

variable "wg_subnet" {
  description = "WireGuard tunnel subnet (edge .1, customer .2)."
  type        = string
  default     = "10.10.0.0/24"
}

variable "wg_listen_port" {
  description = "WireGuard listen port on the edge box."
  type        = number
  default     = 51820
}

variable "edge_ipv6_subnet" {
  description = "The edge box's routed IPv6 subnet (CIDR). Default: Hetzner's per-server /64. Set this when the operator manages one shared /64 and hands this box a /72 or /96 slice of it (e.g. 2a01:4f8:c17:1:ab00::/72). Must be byte-aligned /64..=/112."
  type        = string
  default     = ""
}
