[package]
name = "fortress-site"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
dioxus = { version = "0.7", features = ["fullstack", "router"] }
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }

dioxus-cli-config = { version = "0.7", optional = true }
axum = { version = "0.8", optional = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] , optional = true }
tower = { version = "0.5", features = ["util"], optional = true }

[features]
default = ["server"]
server = ["dioxus/server", "dep:axum", "dep:tokio", "dep:tower", "dioxus-cli-config"]
web = ["dioxus/web"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
